insert into Accounts (UserId, AccountName, AccountType, Currency) values (32, 'Tiền tiết kiệm', 'Ngân hàng', 'VND');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (27, 'Thẻ tín dụng', 'Thẻ tín dụng', 'VND');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (39, 'Thẻ tín dụng', 'Ngân hàng', 'USD');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (13, 'Tiền tiết kiệm', 'Tiền mặt', 'EUR');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (45, 'Tiền tiết kiệm', 'Ngân hàng', 'VND');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (46, 'Tiền tiết kiệm', 'Thẻ tín dụng', 'EUR');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (7, 'Tài khoản thanh toán', 'Ngân hàng', 'EUR');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (2, 'Tài khoản thanh toán', 'Thẻ tín dụng', 'VND');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (40, 'Ví tiền', 'Thẻ tín dụng', 'USD');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (11, 'Ví tiền', 'Thẻ tín dụng', 'USD');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (8, 'Ví tiền', 'Thẻ tín dụng', 'VND');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (44, 'Thẻ tín dụng', 'Thẻ tín dụng', 'EUR');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (17, 'Thẻ tín dụng', 'Ngân hàng', 'EUR');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (18, 'Ví tiền', 'Ngân hàng', 'VND');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (15, 'Thẻ tín dụng', 'Thẻ tín dụng', 'VND');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (28, 'Ví tiền', 'Tiền mặt', 'USD');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (37, 'Tiền tiết kiệm', 'Ngân hàng', 'VND');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (47, 'Ví tiền', 'Thẻ tín dụng', 'VND');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (38, 'Tài khoản thanh toán', 'Tiền mặt', 'EUR');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (33, 'Thẻ tín dụng', 'Thẻ tín dụng', 'USD');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (1, 'Thẻ tín dụng', 'Tiền mặt', 'USD');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (21, 'Thẻ tín dụng', 'Tiền mặt', 'EUR');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (16, 'Thẻ tín dụng', 'Ngân hàng', 'VND');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (34, 'Thẻ tín dụng', 'Ngân hàng', 'EUR');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (23, 'Thẻ tín dụng', 'Thẻ tín dụng', 'VND');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (3, 'Tài khoản thanh toán', 'Ngân hàng', 'EUR');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (42, 'Tiền tiết kiệm', 'Tiền mặt', 'USD');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (29, 'Tài khoản thanh toán', 'Ngân hàng', 'VND');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (49, 'Tài khoản thanh toán', 'Ngân hàng', 'EUR');
insert into Accounts (UserId, AccountName, AccountType, Currency) values (12, 'Tiền tiết kiệm', 'Ngân hàng', 'VND');
